In [55]:
# Backpropagation
# 影片看一次 https://www.youtube.com/watch?v=ibJpTrp5mcE
# python實作(抄)一次  https://www.youtube.com/watch?v=q555kfIFUCM&t=2s
    

In [56]:
import numpy as np
x = np.array([
        [0,0,1],
        [0,1,1],
        [1,0,1],
        [1,1,1]
    ])

y = np.array([
        [0],
        [1],
        [1],
        [0]
    ])

In [57]:
epochs = 60000

In [58]:
# 配合sigmoid 產生-1~1之間的亂數
w0 = 2*np.random.random((3, 4))-1 #這裡先做了轉置
w1 = 2*np.random.random((4, 1))-1

print(w0)
print(w1)

[[-0.51298588  0.95943061 -0.53982614  0.34497632]
 [-0.03026859 -0.36448621  0.30366604  0.73792319]
 [ 0.08978935  0.09225067 -0.58144177  0.00866042]]
[[-0.14409916]
 [-0.7625425 ]
 [ 0.00603933]
 [ 0.18703952]]


In [59]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def dsigmoid(x):
    return x*(1-x)

In [60]:
for j in range(epochs):
    # Forward Pass
    L0 = x
    L1 = sigmoid(np.dot(L0, w0))
    L2 = sigmoid(np.dot(L1, w1))

    # Error
    L2_error = y - L2

    if (j % 10000) == 0:
        print("Error:" + str(np.mean(np.abs(L2_error))))

    # Backward Pass
    # case 1 : output layer
    L2_error = y - L2
    L2_delta = -L2_error * dsigmoid(L2) #微分後應該要加負號 https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/
    
    # case 2 : not output layer
    L1_error = np.dot(L2_delta, w1.T)
    L1_delta = L1_error * dsigmoid(L1)

    # Forward Pass * Backward Pass
    w1 = w1 - np.dot(L1.T, L2_delta) #原作者用加的，因為它省略前面的負號，負負得正
    w0 = w0 - np.dot(L0.T, L1_delta)

Error:0.498981634666
Error:0.0109409062473
Error:0.00717448723262
Error:0.00565535575963
Error:0.00479168653991
Error:0.0042200596379


In [61]:
print(L2)

[[ 0.0015232 ]
 [ 0.99578136]
 [ 0.99541593]
 [ 0.00490356]]


In [62]:
print(y)

[[0]
 [1]
 [1]
 [0]]
