In [4]:
# http://beanobody.blogspot.tw/2017/04/graphvizs-executables-not-found.html

import os
os.environ['PATH'] = os.environ['PATH'] + (';c:\\Program Files (x86)\\Graphviz2.38\\bin\\')

In [5]:
# https://www.youtube.com/watch?v=tNa99PG8hR8

import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()

test_idx = [0, 50 ,100]

train_data = np.delete(iris.data, test_idx, axis = 0)
train_target = np.delete(iris.target, test_idx, axis = 0)

test_data = iris.data[test_idx]
test_target = iris.data[test_idx]

clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

print(clf.predict(test_data))
print(test_target)

[0 1 2]
[[ 5.1  3.5  1.4  0.2]
 [ 7.   3.2  4.7  1.4]
 [ 6.3  3.3  6.   2.5]]


In [6]:
from sklearn.externals.six import StringIO
import pydotplus
dot_data = StringIO()
tree.export_graphviz(clf,
                    out_file=dot_data,
                    feature_names=iris.feature_names,
                    class_names=iris.target_names,
                    filled=True,
                    rounded=True,
                    impurity=False)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")

True

In [7]:
pwd

'C:\\Users\\S4364\\Documents'